/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "secondary": "#ffb3ad",
        "surface-container-low": "#181c24",
        "tertiary-fixed-dim": "#ffb95f",
        "error": "#ffb4ab",
        "on-primary-container": "#00422b",
        "surface-container-lowest": "#0a0e16",
        "surface-dim": "#0f131c",
        "on-tertiary": "#472a00",
        "surface-container-high": "#262a33",
        "surface": "#0f131c",
        "on-secondary-fixed-variant": "#930013",
        "on-background": "#dfe2ee",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-container": "#523200",
        "inverse-primary": "#006c49",
        "on-surface": "#dfe2ee",
        "surface-variant": "#31353e",
        "error-container": "#93000a",
        "tertiary": "#ffb95f",
        "surface-container": "#1c2028",
        "outline-variant": "#3c4a42",
        "primary": "#4edea3",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#410004",
        "surface-tint": "#4edea3",
        "on-primary-fixed": "#002113",
        "inverse-on-surface": "#2c3039",
        "on-secondary-container": "#ffaea8",
        "secondary-fixed-dim": "#ffb3ad",
        "secondary-container": "#a40217",
        "tertiary-container": "#e29100",
        "background": "#0f131c",
        "surface-bright": "#353942",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary": "#68000a",
        "secondary-fixed": "#ffdad7",
        "on-primary-fixed-variant": "#005236",
        "inverse-surface": "#dfe2ee",
        "surface-container-highest": "#31353e",
        "primary-container": "#10b981",
        "on-primary": "#003824",
        "tertiary-fixed": "#ffddb8",
        "primary-fixed-dim": "#4edea3",
        "primary-fixed": "#6ffbbe",
        "on-surface-variant": "#bbcabf",
        "outline": "#86948a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "gutter-desktop": "1rem",
        "space-sm": "0.5rem",
        "col-min-width": "18rem",
        "gutter-mobile": "0.75rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-base": "1rem",
        "space-xxs": "0.125rem"
      },
      fontFamily: {
        "label-numeric-sm": ["JetBrains Mono", "monospace"],
        "label-numeric-md": ["JetBrains Mono", "monospace"],
        "label-numeric-lg": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "caption-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-numeric-sm": ["11px", { lineHeight: "14px", letterSpacing: "0em", fontWeight: "500" }],
        "label-numeric-md": ["13px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-numeric-lg": ["16px", { lineHeight: "20px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-xl": ["32px", { lineHeight: "38px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "caption-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
